#!/usr/bin/perl

use warnings;
use strict;
use Getopt::Long;
use File::Basename;
use Pod::Usage;
use fralib;

=head1 NAME

sa2kml

=head1 SYNOPSIS

    usage: sa2kml [options] <population-annotation-file>
	
       v - verbose
       d - debug
       c - color mapping file (required)
       	   a)<field-name>
       	   b)color
       f - field name
       	   
       <population-annotation-file> 
         - population annotation file
           a)population-id
           b)latitude
           c)longitude
           ... misc ...
           
       example: sa2kml -c color-mapping.txt pscalare.pop
       
       Generates a kml file.
       
=head1 DESCRIPTION

=cut

#option variables
my $verbose;
my $debug;
my $help;
my $popAnnotationFile;
my $colorMappingFile;
my $fieldName;

#data structures
my %POP;
my %LANG;
my $colNo;
my %label2col;
my @columnToLabel;
my %COLOR;

#initialize options
Getopt::Long::Configure ('bundling');

$COLOR{orange} = "FF4C99FF";
$COLOR{black} = "FF000000";
$COLOR{blue} = "FFE69900";
$COLOR{yellow} = "FF00FFE6";
$COLOR{pink} = "FFE699FF";
$COLOR{green} = "FF339933";
$COLOR{purple} = "FF7F007F";
$COLOR{red} = "FF4C00FF";
$COLOR{lightGreen} = "FF00FF00";
$COLOR{darkBlue} = "FFFF0000";
$COLOR{lightPurple} = "FFFF00FF";
$COLOR{lightYellow} = "FF99E6FF";
$COLOR{brown} = "FF004CB3";
$COLOR{lightBlue} = "FFFFFF00";
$COLOR{oliveGreen} = "FF007F7F";
$COLOR{peach} = "FF9999FF";
$COLOR{seaGreen} = "FF7F7F00";
$COLOR{yellowGreen} = "FF26BF99";
$COLOR{bluePurple} = "FFE62673";
$COLOR{blueGreen} = "FF99BF26";
$COLOR{gray} = "FF808080";
$COLOR{darkGreen} = "FF0C660C";
$COLOR{lightGray} = "FFC0C0C0";
$COLOR{red2} = "FF0000FF";
$COLOR{lightBlue2} = "FFFFE699";
$COLOR{lightOrange} = "FF6699FF";
$COLOR{darkGray} = "FF3D3D3D";
$COLOR{lightPink} = "FFE6E6FF";
$COLOR{darkBrown} = "FF333399";
$COLOR{darkOrange} = "FF0066FF";
$COLOR{darkPurple} = "FF4C0033";
    
if(!GetOptions ('h' => \$help, 'v'=>\$verbose,'d'=>\$debug, 'c=s'=>\$colorMappingFile, 'f=s'=>\$fieldName) 
|| !defined($fieldName)
|| !defined($colorMappingFile) 
|| scalar(@ARGV)!=1)
{
    if ($help)
    {
        pod2usage(-verbose => 2);
    }
    else
    {
        pod2usage(1);
    }
}

	print <<HEADERSTART;
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.1">
<Document>
	<name>NAME</name>

		<StyleMap id="default_copy1-0">
			<Pair>
				<key>normal</key>
				<styleUrl>#default_copy1-2</styleUrl>
			</Pair>
			<Pair>
				<key>highlight</key>
				<styleUrl>#default_copy1-1</styleUrl>
			</Pair>
		</StyleMap>
		<Style id="default_copy1-1">
			<IconStyle>
				<color>FF0000FF</color>
				<scale>1.3</scale>
				<Icon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>FF0000FF</color>
			</LabelStyle>
			<ListStyle>
				<ItemIcon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank-lv.png</href>
				</ItemIcon>
			</ListStyle>
		</Style>
		<Style id="default_copy1-0">
			<IconStyle>
				<color>FF0000FF</color>
				<scale>1.1</scale>
				<Icon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>
				</Icon>
				<hotSpot x="32" y="1" xunits="pixels" yunits="pixels"/>
			</IconStyle>
			<LabelStyle>
				<color>FF0000FF</color>
			</LabelStyle>
			<ListStyle>
				<ItemIcon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank-lv.png</href>
				</ItemIcon>
			</ListStyle>
		</Style>

HEADERSTART

open(COLOR, "$colorMappingFile") || die "Cannot open $colorMappingFile";
while(<COLOR>)
{
	s/\r?\n?$//;
	
	if($.==1)
	{
		$colNo = s/\t/\t/g + 1;
		
		my @fields = split('\t', $_, $colNo);			

		SEARCH_LABEL: for my $label ($fieldName, 'color')
		{
			for my $col (0 .. $#fields)
			{
				if ($fields[$col] eq $label)
				{			
					$label2col{$label}=$col;
					next SEARCH_LABEL;
				}
			}
			
			die "Cannot find '$label' in $colorMappingFile";
		}
	}
	else
	{
		my @fields = split('\t', $_, $colNo);
		my $field = $fields[$label2col{$fieldName}];
		my $color = "000000FF";
		
		if (exists($COLOR{$fields[$label2col{'color'}]}))
		{
			$color = $COLOR{$fields[$label2col{'color'}]};
		}
		
		my $ref = $.;
		$LANG{$field} = "default_copy$ref-0";
		
		print <<STYLEMAP;
		<StyleMap id="default_copy$ref-0">
			<Pair>
				<key>normal</key>
				<styleUrl>#default_copy$ref-2</styleUrl>
			</Pair>
			<Pair>
				<key>highlight</key>
				<styleUrl>#default_copy$ref-1</styleUrl>
			</Pair>
		</StyleMap>
		<Style id="default_copy$ref-1">
			<IconStyle>
				<color>$color</color>
				<scale>1.3</scale>
				<Icon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>$color</color>
			</LabelStyle>
			<ListStyle>
				<ItemIcon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank-lv.png</href>
				</ItemIcon>
			</ListStyle>
		</Style>
		<Style id="default_copy$ref-0">
			<IconStyle>
				<color>$color</color>
				<scale>1.1</scale>
				<Icon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>
				</Icon>
				<hotSpot x="32" y="1" xunits="pixels" yunits="pixels"/>
			</IconStyle>
			<LabelStyle>
				<color>$color</color>
			</LabelStyle>
			<ListStyle>
				<ItemIcon>
					<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank-lv.png</href>
				</ItemIcon>
			</ListStyle>
		</Style>
STYLEMAP

	}
}
close(COLOR);

	print <<FOLDERSTART;
	<Folder>
		<name>NAME TO BE REPLACED</name>
		<open>1</open>
FOLDERSTART

$popAnnotationFile = $ARGV[0];

open(IN, "$popAnnotationFile") || die "Cannot open $popAnnotationFile";
while(<IN>)
{
	s/\r?\n?$//;
	
	if($.==1)
	{
		$colNo = s/\t/\t/g + 1;
		
		my @fields = split('\t', $_, $colNo);			

		SEARCH_LABEL: for my $label ('population-id', 'ethnicity', 'latitude', 'longitude')
		{
			for my $col (0 .. $#fields)
			{
				if ($fields[$col] eq $label)
				{			
					next SEARCH_LABEL;
				}
			}
						
			die "Cannot find '$label' in $popAnnotationFile";
		}
		
		#extract all labels
	    for my $col (0 .. $#fields)
		{
			$label2col{$fields[$col]}=$col;
			$columnToLabel[$col] = $fields[$col];
		}
	}
	else
	{
		my @fields = split('\t', $_, $colNo);
		my $popId = $fields[$label2col{'population-id'}];
		my $ethnicity = $fields[$label2col{'ethnicity'}];
		my $latitude = $fields[$label2col{'latitude'}];
		my $longitude = $fields[$label2col{'longitude'}];
		my $field = $fields[$label2col{$fieldName}];
			
		my $numericalLatitude;
		my $numericalLongitude;
					
		#calculate coordinates
		if ($latitude=~/(\d+).\s+(\d+)'\s+(\d+|\d+\.\d+)''\s+([NS])/)
		{
			$numericalLatitude = $1 + ($2*60+$3)/3600;
			
			if($4 eq 'S')
			{
				$numericalLatitude = -$numericalLatitude;
			}
		}
		elsif ($latitude=~/(\d+).\s+(\d+)'\s+([NS])/)
		{
			$numericalLatitude = $1 + ($2*60)/3600;
			
			if($3 eq 'S')
			{
				$numericalLatitude = -$numericalLatitude;
			}
		}
		elsif ($latitude=~/(\d+).\s+([NS])/)
		{
			$numericalLatitude = $1;
			
			if($2 eq 'S')
			{
				$numericalLatitude = -$numericalLatitude;
			}
		}
		else
		{
			die "Improper latitude coordinates: $latitude";
		}

		if ($longitude=~/(\d+).\s+(\d+)'\s+(\d+|\d+\.\d+)''\s+([EW])/)
		{
			$numericalLongitude = $1 + ($2*60+$3)/3600;
			
			if($4 eq 'W')
			{
				$numericalLongitude = -$numericalLongitude;
			}
		}
		elsif ($longitude=~/(\d+).\s+(\d+)'\s+([EW])/)
		{
			$numericalLongitude = $1 + ($2*60)/3600;
			
			if($3 eq 'W')
			{
				$numericalLongitude = -$numericalLongitude;
			}
		}
		elsif ($longitude=~/(\d+).\s+([EW])/)
		{
			$numericalLongitude = $1;
			
			if($2 eq 'W')
			{
				$numericalLongitude = -$numericalLongitude;
			}
		}
		else
		{
			die "Improper numerical coordinates: $longitude";
		}
				
		print <<PLACEMARK;
			<Placemark>
			    <name>$popId ($ethnicity)</name>
			    <description>
PLACEMARK
		
		for my $col (0 .. $#fields)
		{
		    if($columnToLabel[$col]!~/^(population-id|ethnicity|latitude|longitude)$/)
		    {
		        print "$columnToLabel[$col]: $fields[$col]\n"
		    }
		}

        print <<PLACEMARK;
                </description>
			    <styleUrl>#$LANG{$field}</styleUrl>
			    <Point>
			        <coordinates>$numericalLongitude,$numericalLatitude,0</coordinates>
			    </Point>
			</Placemark>
PLACEMARK

	}
}

print <<FOLDEREND;
		</Folder>
	</Document>
</kml>
FOLDEREND

close(IN);