#!/usr/bin/perl

use warnings;
use strict;
use fralib;
use Getopt::Long;
use Pod::Usage;
use File::Basename;
use Switch;

=head1 NAME

tg2illumina

=head1 SYNOPSIS

 tg2illumina [options] tg-file
    
  -m        marker annotation file
            a)snp-id
            b)alleles
  tg-file   tg file
  
 example: tg2illumina -m pscalare.mk pscalare.tg
    
 Converts tg file to illumina matrix file.
       
=head1 DESCRIPTION
 
=cut

#option variables
my $help;
my $mkFile;
my $tgFile;
my $illuminaFile;
my %SNP;
my $colNo;
my %label2Column;
my $headerProcessed;

#initialize options
Getopt::Long::Configure ('bundling');

if(!GetOptions ('h'=>\$help, 'm=s'=>\$mkFile)
   || !defined($mkFile)
   || scalar(@ARGV)!=1)
{
    if ($help)
    {
        pod2usage(-verbose => 2);
    }
    else
    {
        pod2usage(1);
    }
}

$tgFile = $ARGV[0];

#checks if input is genotype file
isTg($tgFile) || die "$tgFile is not a tg file";
    
open(MK, $mkFile) || die "Cannot open $mkFile";
$headerProcessed = 0;
while(<MK>)
{
    s/\r?\n?$//;
    
    if(!$headerProcessed)
    {
        $colNo = s/\t/\t/g + 1;
        
        my @fields = split('\t', $_, $colNo);
        
        SEARCH_LABEL: for my $label ('snp-id', 'alleles')
        {
            for my $col (0 .. $#fields)
            {
                if ($fields[$col] eq $label)
                {           
                    $label2Column{$label}=$col;
                    next SEARCH_LABEL;
                }
            }
            
            die "Cannot find '$label' in $mkFile";
        }
        
        $headerProcessed = 1;
    }
    else
    {
        my @fields = split('\t', $_, $colNo);
        
        my $snp = $fields[$label2Column{'snp-id'}];
        my $alleles = $fields[$label2Column{'alleles'}];
        
        my @alleles = split('/', $alleles, -1);

        $SNP{$snp}{0} = "$alleles[0]$alleles[0]";
        $SNP{$snp}{1} = "$alleles[0]$alleles[1]";
        $SNP{$snp}{2} = "$alleles[1]$alleles[1]";
    }
}
close(MK);

open(TG, "$tgFile") || die "Cannot open $tgFile\n";
$headerProcessed = 0;
if(!defined($illuminaFile))  
{
  my ($name, $path, $ext) = fileparse($tgFile, '\..*');
  $illuminaFile = "illumina-$name.txt";
}
open(ILLUMINA, ">$illuminaFile") || die "Cannot open $illuminaFile\n";

while (<TG>)
{
    s/\r?\n?$//;
   
    if(!$headerProcessed)
    {
        #counts number of columns
        $colNo = s/\t/\t/g + 1;
        
        my @fields = split('\t', $_, $colNo);
         
        print ILLUMINA "$_\n";
        
        $headerProcessed = 1;
    }
    else
    {
        my @fields = split('\t', $_, $colNo);
    
    	my $snpID = $fields[0];
    
        print ILLUMINA "$snpID";
               
        for my $col (1..$#fields)
        {
        	if ($fields[$col]!=-1)
        	{
        		print ILLUMINA "\t$SNP{$snpID}{$fields[$col]}";
        	}
        	else
        	{
        		print ILLUMINA "\t--";
        	}            
        }
        
        print ILLUMINA "\n";
    }
}

close(ILLUMINA);
close(TG);